package uk.ac.cam.darknet.backend;

import java.util.List;

import uk.ac.cam.darknet.common.Individual;
import uk.ac.cam.darknet.common.Properties;
import uk.ac.cam.darknet.database.DatabaseManager;

/**
 * This class is a primary data collector with a graphical user interface
 * allowing manual data input. It represents the primary way of entering data
 * into the system. This collector supports reading comma-separated values (CSV)
 * files generated by booking systems.
 * 
 * @author Augustin Zidek
 * 
 */
public class ManualInputDataCollector extends PrimaryDataCollector {
	/**
	 * Create a new manual data collector with the specified database manager.
	 * 
	 * @param databaseManager The database manager to use to write to the
	 *            database.
	 */
	public ManualInputDataCollector(DatabaseManager databaseManager) {
		super(databaseManager);
		// TODO Auto-generated constructor stub
	}

	@Override
	public void run() {
		// TODO Auto-generated method stub
	}

	@Override
	public void setup(List<Individual> individuals) {
		// TODO Auto-generated method stub
	}

	@Override
	public Properties getTypeTable() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getCollectorId() {
		// TODO Auto-generated method stub
		return null;
	}
}
